### PR TITLE
fix some php 8.1 deprecations

### PR DESCRIPTION
**Pull request by 0cool-f**

### CODE REVIEW

**Comment by robiso** [comment]
Hello  @0cool-f!

Since only the error logs are filling up and WonderCMS is still functioning normally, we plan on releasing full PHP 8.2 support by the end of year (PHP 8.2 should be released in November 24).

If we currently do the upgrade, we would break about 10-20% of our user base (WonderCMS would stop functioning for them). There's an issue opened which we'll tackle after 8.2 is released.

We'll keep this pull request still open and appropriately list you on our https://wondercms.com/contributors page.

Thank you.

**Comment by robiso** [comment]
Linked issue: https://github.com/robiso/wondercms/issues/268

**Comment by robiso** [comment]
New pull request with 8.2 support changes.

**Comment by robiso** [comment]
@0cool-f if you're interested, there were additional changes made: https://github.com/WonderCMS/wondercms/pull/280/commits/f6a3d6b1907869044cf7bd097b0f2e5850dd33f6

If you can, please share your first/last name and website so we can link to it here: https://www.wondercms.com/contributors

**Comment by 0cool-f** [comment]
Sure: Fabio Di Giorgio, https://www.linkedin.com/in/fdigiorgio/
Thanks! 😊

**Comment by robiso** [comment]
@0cool-f, thank you! You've been added: https://www.wondercms.com/contributors :)

**Pull request closed without merging**
